#include <string.h>
#include "include/gaw_player.h"
#include "include/gaw_core.h"
#include "include/gaw_platform.h"
#include "include/gaw_ram.h"
#include "include/gaw_world_progress.h"
#include "include/gaw_world.h"

/* ROM-derived tables. Generated by tools/gen_phase5_tables.py. */
static const uint8_t player_motion_normal[6*17] = {
#include "player_motion_normal.inc"
};
static const uint8_t player_motion_alt[6*17] = {
#include "player_motion_alt.inc"
};
static const uint16_t player_sprite_normal[256] = {
#include "player_sprite_normal.inc"
};
static const uint16_t player_sprite_mode3[8] = {
#include "player_sprite_mode3.inc"
};
static const uint16_t player_sprite_death[2] = {
#include "player_sprite_death.inc"
};
static const uint16_t player_sprite_state11[8] = {
#include "player_sprite_state11.inc"
};
static const uint8_t player_action_anim[44] = {
#include "player_action_anim.inc"
};
static const uint8_t player_stat_lookup[48] = {
#include "player_stat_lookup.inc"
};
static const uint8_t player_contact_thresholds[64] = {
#include "player_contact_thresholds.inc"
};
static const uint8_t player_world_action_tiles[][4] = {
#include "player_world_action_tiles.inc"
};

#define R8(a) gaw_ram_read8((a))
#define W8(a,v) gaw_ram_write8((a),(v))

static int bit7(unsigned off) { return (R8((uint16_t)(RAM_PLAYER_TILE_FLAGS + off)) & 0x80u) != 0; }

/* $232F: address one cell in the 16x16 byte world-tile grid at $DC00. */
static uint16_t player_world_tile_addr(const GawEntity *e, int8_t yoff, int8_t xoff) {
    uint8_t y=(uint8_t)(e->raw[0x13]+(uint8_t)yoff);
    uint8_t x=(uint8_t)(e->raw[0x11]+(uint8_t)xoff);
    return (uint16_t)(0xDC00u | (uint16_t)(x&0xF0u) | (uint16_t)((y&0xF0u)>>4));
}

/* $230E: locate a 16-bit metatile descriptor in the $D600 map buffer. */
static uint16_t player_map_descriptor_addr(const GawEntity *e, int8_t yoff, int8_t xoff) {
    uint8_t x=(uint8_t)(e->raw[0x11]+(uint8_t)xoff);
    uint8_t y=(uint8_t)(e->raw[0x13]+(uint8_t)yoff);
    uint16_t off=(uint16_t)((uint16_t)(x&0xF8u)<<3);
    off=(uint16_t)(off + (uint16_t)(((uint8_t)(y>>2))&0x3Eu));
    return (uint16_t)(0xD600u+off);
}

static int tile_in_list(uint8_t tile, const uint8_t *list, unsigned n) {
    for (unsigned i=0;i<n;++i) if (list[i]==tile) return 1;
    return 0;
}

/* $386E/$3885 and the records at $2544/$2569. */
static uint8_t player_classify_environment(uint8_t base_mode) {
    static const uint8_t a0[]={0x2F,0x83}, a1[]={0xA0,0xA1};
    static const uint8_t a2[]={0x11,0x12,0x93,0x94,0x99,0xB9};
    static const uint8_t a3[]={0x7F,0x80,0x81,0x82};
    static const uint8_t a4[]={0xBA,0xBB,0xBC,0xBD,0xBE,0xBF};
    static const uint8_t b0[]={0xFF}, b1[]={0x0C,0x0D,0x0E,0x0F,0x10,0x11};
    static const uint8_t b2[]={0xFF}, b3[]={0x78,0x79,0x7A,0x7B,0x7C,0x7D,0x7E,0x7F};
    static const uint8_t b4[]={0xFF};
    const uint8_t *lists_a[5]={a0,a1,a2,a3,a4};
    const uint8_t lens_a[5]={2,2,6,4,6};
    const uint8_t *lists_b[5]={b0,b1,b2,b3,b4};
    const uint8_t lens_b[5]={1,6,1,8,1};
    const uint8_t **lists=base_mode<1?lists_a:lists_b;
    const uint8_t *lens=base_mode<1?lens_a:lens_b;
    uint8_t t0=R8(0xC052), t1=R8(0xC054);
    for (unsigned i=0;i<5;++i) {
        int hit0=tile_in_list(t0,lists[i],lens[i]);
        int hit1=tile_in_list(t1,lists[i],lens[i]);
        int match=(i==1 || i==2) ? (hit0&&hit1) : (hit0||hit1);
        if (match) return (uint8_t)(i+1u);
    }
    return 0;
}

static uint8_t player_attack_from_inventory(void) {
    uint8_t item=R8(0xC0DF);
    uint8_t level=R8((uint16_t)(0xC0E0u+item));
    unsigned idx=(unsigned)item*4u+level;
    return idx<sizeof player_stat_lookup ? player_stat_lookup[idx] : 0;
}

/* Native $2C8D: rebuild the local 3x8 terrain cache and environment mode. */
static void player_environment_preprocess(GawEntity *e) {
    uint8_t f2=R8(0xC0F2), f1=R8(0xC0F1);
    uint8_t l=(uint8_t)((uint8_t)(f2-1u)<<1);
    uint8_t h=(uint8_t)((uint8_t)(f1-1u)<<2);
    if (R8(0xC0BF)!=0) h=0;
    e->raw[ENT_DEFENSE]=(uint8_t)(h+l);
    e->raw[ENT_ATTACK]=player_attack_from_inventory();

    uint8_t x=e->raw[0x11], y=e->raw[0x13];
    uint8_t quadrant=(uint8_t)(((y&8u)>>3)|((x&8u)>>2));
    if (((x|y)&7u)!=0) quadrant|=0x80u;
    W8(0xC06B,quadrant);

    /* $230E returns HL on the descriptor's second byte after loading DE;
       the following DEC L returns to the first byte.  Our address helper
       already returns that first byte, so no extra decrement belongs here. */
    uint16_t src=player_map_descriptor_addr(e,-12,-12);
    uint16_t dst=RAM_PLAYER_TILE_FLAGS;
    for (unsigned row=0;row<3;++row) {
        for (unsigned i=0;i<8;++i) W8(dst++,R8(src++));
        src=(uint16_t)(src+0x38u);
    }
    gaw_ram_write16le(0xC060,(uint16_t)(src+0x29BEu));

    if (R8(0xC0EC)==0) {
        for (unsigned i=1;i<24;i+=2) if (R8((uint16_t)(RAM_PLAYER_TILE_FLAGS+i))&0x20u)
            W8((uint16_t)(RAM_PLAYER_TILE_FLAGS+i),(uint8_t)(R8((uint16_t)(RAM_PLAYER_TILE_FLAGS+i))|0x80u));
    }

    uint8_t base=R8(0xC040);
    uint8_t mode=(base==1)?0:player_classify_environment(base);
    W8(RAM_PLAYER_ENV_MODE,mode);

    if (R8(0xC0F0)!=0) {
        uint8_t a=(uint8_t)(R8(0xC053)&R8(0xC055)&0xC0u);
        if (a&0x40u) {
            int toggle=(a&0x80u)!=0;
            for (unsigned i=1;i<24;i+=2) {
                uint16_t addr=(uint16_t)(RAM_PLAYER_TILE_FLAGS+i);
                uint8_t v=R8(addr);
                if (v&0x40u) v&=(uint8_t)~0x80u;
                else if (toggle) v|=0x80u;
                W8(addr,v);
            }
        }
    }
}

/* $2C63-$2D7B: gameplay-entry construction of Arthur.  The original
   intentionally calls $369F before rebuilding C041 with $2C8D, so preserve
   that ordering here. */
void gaw_player_init_from_world(void) {
    GawEntity *e=gaw_entity(0);
    if (!e) return;
    e->raw[0x12]=0;
    e->raw[0x10]=0;
    e->raw[ENT_MOTION_PHASE]=0;
    e->raw[ENT_ANIM_FRAMES]=0;
    e->raw[ENT_ANIM_FRAME]=0;
    e->raw[ENT_TYPE]=2;
    e->raw[ENT_STATE]=0;
    e->raw[ENT_GFX_ID]=0xF0;
    e->raw[ENT_FLAGS]=0x03;
    gaw_player_update_sprite_meta(e);
    memset(gaw_ram_ptr(0xC330u),0,0x180u);
    player_environment_preprocess(e);
}

/* $38AC: mutate the horizontal $DC00 tile chain used by direction 0. */
static void player_map_mutation_38ac(GawEntity *e) {
    if (R8(0xC040)!=0 || R8(0xC0ED)==0 || R8(0xC06B)!=3) return;
    uint16_t addr=player_world_tile_addr(e,0,-16);
    if (R8(addr)!=0x02) return;
    uint8_t count=1;
    W8(addr,0x6D);
    for (;;) {
        uint8_t lo=(uint8_t)addr;
        if (lo<0x10u) break;
        lo=(uint8_t)(lo-0x10u); addr=(uint16_t)((addr&0xFF00u)|lo);
        if (R8(addr)!=0x0C) break;
        W8(addr,0x6C); ++count;
    }
    gaw_ram_write16le(0xC098,(uint16_t)(((uint16_t)(uint8_t)(count<<1)<<8)|0x03u));
    W8(0xC09A,(uint8_t)(e->raw[0x11]-0x10u));
    W8(0xC09B,(uint8_t)(e->raw[0x13]-0x08u));
}

/* $38F6: mutate the vertical/forward $DC00 tile chain used by direction 1. */
static void player_map_mutation_38f6(GawEntity *e) {
    if (R8(0xC040)!=0 || R8(0xC0ED)==0 || R8(0xC06B)!=1) return;
    uint16_t addr=player_world_tile_addr(e,0,0);
    if (R8(addr)!=0x0C) return;
    uint8_t count=0;
    for (;;) {
        uint8_t old=R8(addr);
        W8(addr,0x6C); ++count;
        if (old==0x02) { W8(addr,0x6D); break; }
        uint8_t lo=(uint8_t)((uint8_t)addr+0x10u);
        addr=(uint16_t)((addr&0xFF00u)|lo);
        if (lo>=0xA0u) break;
    }
    gaw_ram_write16le(0xC098,(uint16_t)(((uint16_t)(uint8_t)(count<<1)<<8)|0x04u));
    W8(0xC09A,e->raw[0x11]);
    W8(0xC09B,(uint8_t)(e->raw[0x13]-0x08u));
}

/* Exact branch structure of $3321/$3341/$3360/$338D after the optional
   map-side-effect calls. Returns -1 when movement is blocked. */
static int player_resolve_direction(uint8_t requested, uint8_t *resolved, GawEntity *e) {
    switch (requested & 3u) {
        case 0:
            player_map_mutation_38ac(e);
            if (!bit7(3)) {
                if (!bit7(5)) { *resolved=0; return 1; }
                if (bit7(9)) return -1;
                *resolved=2; return 1;
            }
            if (bit7(5) || bit7(15)) return -1;
            *resolved=3; return 1;
        case 1:
            player_map_mutation_38f6(e);
            if (!bit7(21)) {
                if (!bit7(19)) { *resolved=1; return 1; }
                if (bit7(15)) return -1;
                *resolved=3; return 1;
            }
            if (bit7(19) || bit7(9)) return -1;
            *resolved=2; return 1;
        case 2:
            if (!bit7(9)) { *resolved=2; return 1; }
            if (!bit7(1) && !bit7(3) && !bit7(5)) { *resolved=0; return 1; }
            if (bit7(17) || bit7(19) || bit7(21)) return -1;
            *resolved=1; return 1;
        default:
            if (!bit7(15)) { *resolved=3; return 1; }
            if (!bit7(7) && !bit7(5) && !bit7(3)) { *resolved=0; return 1; }
            if (bit7(23) || bit7(21) || bit7(19)) return -1;
            *resolved=1; return 1;
    }
}

void gaw_player_update_sprite_meta(GawEntity *e) {
    uint8_t mode=R8(RAM_PLAYER_ENV_MODE);
    if (mode == 3) {
        unsigned idx=((unsigned)(e->raw[ENT_DIRECTION]&3u)<<1) | (e->raw[ENT_ANIM_FRAME]&1u);
        W8(RAM_PLAYER_SPRITE_BANK,5);
        gaw_ram_write16le(RAM_PLAYER_SPRITE_PTR,player_sprite_mode3[idx]);
        e->raw[0x08]=0xA0; e->raw[0x09]=0x80;
        return;
    }

    uint8_t c=0;
    if (R8(0xC0DF)==1) c=(uint8_t)(R8(0xC0E1)+1u);
    if (mode==2) c|=4u;
    gaw_ram_write16le(0xC308,(uint16_t)(0x80A0u + (uint16_t)c*8u));
    unsigned idx=((((unsigned)c*4u)|(e->raw[ENT_DIRECTION]&3u))*8u) | e->raw[ENT_ANIM_FRAME];
    if (mode==5) idx &= 0xE7u;
    idx &= 0xFFu;
    gaw_ram_write16le(RAM_PLAYER_SPRITE_PTR,player_sprite_normal[idx]);
    W8(RAM_PLAYER_SPRITE_BANK,(uint8_t)(4u + ((c&4u)!=0)));
}

static void player_state_walk(GawEntity *e) {
    if (e->raw[ENT_MOTION_PHASE] != 0) { gaw_player_update_sprite_meta(e); return; }
    gaw_entity_set16(e,ENT_DELTA0,0);
    gaw_entity_set16(e,ENT_DELTA1,0);

    uint8_t requested=0;
    uint8_t current=e->raw[ENT_DIRECTION]&3u;
    uint8_t forced=R8(RAM_PLAYER_FORCED_DIR);
    if (forced & 0x80u) {
        current=(uint8_t)(forced&3u);
        W8(RAM_PLAYER_FORCED_DIR,current);
    }
    static const uint8_t mask[4]={1,2,4,8};
    uint8_t held=R8(RAM_INPUT_HELD);
    uint8_t a=(uint8_t)(held & mask[current]);
    if (!a) a=held;
    if (a&1u) requested=0;
    else if (a&2u) requested=1;
    else if (a&4u) requested=2;
    else if (a&8u) requested=3;
    else { gaw_player_update_sprite_meta(e); return; }

    e->raw[ENT_DIRECTION]=requested;
    if (held&0x20u) { gaw_player_update_sprite_meta(e); return; }

    uint8_t mode=R8(RAM_PLAYER_ENV_MODE);
    if (mode>5) { gaw_player_update_sprite_meta(e); return; }
    const uint8_t *table=R8(0xC0EE)?player_motion_alt:player_motion_normal;
    const uint8_t *rec=&table[(unsigned)mode*17u];
    e->raw[ENT_MOTION_PHASE]=rec[0];
    gaw_ram_write16le(RAM_PLAYER_MOTION_PTR,(uint16_t)((R8(0xC0EE)?0x3441u:0x33DBu)+mode*17u+1u));

    uint8_t resolved=requested;
    if (player_resolve_direction(requested,&resolved,e)>0) {
        if (resolved!=requested) W8(RAM_PLAYER_FORCED_DIR,(uint8_t)(requested|0x80u));
        e->raw[ENT_DIRECTION]=resolved;
        memcpy(&e->raw[ENT_DELTA0],&rec[1u+(unsigned)resolved*4u],4);
    }
    /* $3309 advances the walk pose whenever a movement attempt starts,
       including attempts rejected by the terrain checks. */
    e->raw[ENT_ANIM_FRAME]=(uint8_t)((e->raw[ENT_ANIM_FRAME]+1u)&3u);
    gaw_player_update_sprite_meta(e);
}

static void player_animation_step(GawEntity *e, unsigned table_off, unsigned table_len) {
    uint8_t held=(uint8_t)(R8(RAM_INPUT_HELD)&0x0Fu);
    if (held==1) e->raw[ENT_DIRECTION]=0;
    else if (held==2) e->raw[ENT_DIRECTION]=1;
    else if (held==4) e->raw[ENT_DIRECTION]=2;
    else if (held==8) e->raw[ENT_DIRECTION]=3;

    uint8_t t=(uint8_t)(e->raw[ENT_ANIM_TICK]+1u);
    e->raw[ENT_ANIM_TICK]=t;
    unsigned pos=table_off+t;
    uint8_t frame=(pos<table_off+table_len)?player_action_anim[pos]:0;
    e->raw[ENT_ANIM_FRAME]=frame;
    if (frame==0) { e->raw[ENT_STATE]=0; e->raw[ENT_ANIM_TICK]=0; }
    gaw_player_update_sprite_meta(e);
}


/* $2F18-$2FA7: special aligned-grid transition/rotation sequence. Rendering
   during its 16-frame animation remains a platform-facing legacy boundary. */
static void player_grid_transition(GawEntity *e) {
    if (R8(0xC040)!=0) return;
    uint8_t y=e->raw[0x13], x=e->raw[0x11];
    if (((x|y)&7u)!=0) return;
    uint8_t t0=R8(0xC052), t1=R8(0xC054);
    if (t0==0xB6 || t0==0xB8) y=(uint8_t)(y-8u);
    else if (t0==0xB5 || t0==0xB7) { /* keep y */ }
    else if (t1==0xB5 || t1==0xB7) y=(uint8_t)(y+8u);
    else return;

    e->raw[0x13]=(uint8_t)(y&0xF8u);
    e->raw[0x11]=(uint8_t)(((uint8_t)(x-8u)&0xF0u)|0x08u);
    W8(0xDE06,0xA3);
    for (unsigned i=0;i<16;++i) {
        e->raw[ENT_DIRECTION]=(uint8_t)((e->raw[ENT_DIRECTION]+1u)&3u);
        gaw_player_update_sprite_meta(e);
        e->raw[ENT_FLAGS]|=1u; /* first instruction of $0938 */
        gaw_platform_player_transition_frame();
        gaw_wait_frame();
    }
    e->raw[ENT_STATE]=0;
    uint8_t resource=R8(0xC0DD);
    W8(0xC0DD,resource>=0x1Eu?(uint8_t)(resource-0x1Eu):0);
    uint8_t cell=(uint8_t)((e->raw[0x11]&0xF0u)|((e->raw[0x13]&0xF0u)>>4));
    W8((uint16_t)(0xDC00u+cell),3);
    gaw_world_commit_metatile(cell,3);
}


/* $35B7: write an action-produced tile. If this is the zone's trigger cell,
   commit its metatile immediately, set the persistent bit ($193D), and apply
   the newly-unlocked world patch ($1A7C) only on the first activation. */
static void player_world_action_write(uint8_t cell, uint8_t tile_id) {
    W8((uint16_t)(0xDC00u+cell),tile_id);
    if (cell!=R8(0xC06E)) {
        W8(0xDE06,0x9B);
        return;
    }
    gaw_world_commit_metatile(cell,tile_id);
    if (!gaw_world_progress_test_and_set()) {
        W8(0xDE08,0xA8);
        gaw_world_progress_apply_loaded_patch();
    }
}

/* $358D: action-state-5 tile transformation record at ROM $3620. */
static void player_world_action_try(GawEntity *e, int8_t yoff, int8_t xoff) {
    uint8_t cell=(uint8_t)(player_world_tile_addr(e,yoff,xoff)-0xDC00u);
    uint8_t old=R8((uint16_t)(0xDC00u+cell));
    for (unsigned i=0;player_world_action_tiles[i][0]!=0;++i) {
        const uint8_t *r=player_world_action_tiles[i];
        if (old!=r[0]) continue;
        player_world_action_write(cell,r[1]);
        uint8_t below=(uint8_t)(cell+0x10u);
        if (R8((uint16_t)(0xDC00u+below))==r[2]) player_world_action_write(below,r[3]);
        return;
    }
}

/* $34D3-$35D3. The jump table at $34F0 is direction*4 + C06B quadrant.
   Side effects happen only on animation tick 7. */
static void player_world_action_side_effect(GawEntity *e) {
    if (R8(0xC040)!=0 || e->raw[ENT_ANIM_TICK]!=7) return;
    uint8_t quadrant=R8(0xC06B);
    if (quadrant&0x80u) return; /* original gameplay invariant: aligned here */
    unsigned idx=(unsigned)(e->raw[ENT_DIRECTION]&3u)*4u+(quadrant&3u);
    switch (idx) {
        case 0:
            if (e->raw[0x11]<0x18) return;
            player_world_action_try(e,-32,-16); player_world_action_try(e,-32,0); break;
        case 1:
            if (e->raw[0x11]<0x18) return;
            player_world_action_try(e,-32,-8); break;
        case 2:
            player_world_action_try(e,-24,-16); player_world_action_try(e,-24,0); break;
        case 3:
            player_world_action_try(e,-24,-8); break;
        case 4:
            if (e->raw[0x11]>=0xA0) return;
            player_world_action_try(e,0,-16); player_world_action_try(e,0,0); break;
        case 5:
            if (e->raw[0x11]>=0xA0) return;
            player_world_action_try(e,0,-8); break;
        case 9:
            player_world_action_try(e,-16,-24); break;
        case 10:
            player_world_action_try(e,-24,-16); player_world_action_try(e,-8,-16); break;
        case 11:
            player_world_action_try(e,-24,-24); player_world_action_try(e,-8,-24); break;
        case 13:
            player_world_action_try(e,-16,8); break;
        case 14:
            player_world_action_try(e,-24,0); player_world_action_try(e,-8,0); break;
        case 15:
            player_world_action_try(e,-24,8); player_world_action_try(e,-8,8); break;
        default:
            break; /* original $3558 */
    }
}

static void player_state_dispatch(GawEntity *e) {
    switch (e->raw[ENT_STATE]) {
        case 0: e->raw[ENT_STATE]++; /* fall through */
        case 1: player_state_walk(e); break;
        case 2: e->raw[ENT_ANIM_TICK]=0xFF; e->raw[ENT_STATE]++; /* fall through */
        case 3:
            if (R8(0xC0EE)) player_animation_step(e,13,9);
            else player_animation_step(e,0,13);
            break;
        case 4: e->raw[ENT_ANIM_TICK]=0xFF; e->raw[ENT_STATE]++; /* fall through */
        case 5:
            if (R8(0xC0EE)) player_animation_step(e,35,9);
            else player_animation_step(e,22,13);
            player_world_action_side_effect(e);
            break;
        case 6:
            e->raw[ENT_HIT_FLASH_TIMER]=0;
            e->raw[ENT_PENDING_DAMAGE]=0;
            e->raw[ENT_STATE]++;
            /* fall through */
        case 7:
            if (R8(0xC090)==0) e->raw[ENT_STATE]=0;
            e->raw[0x08]=0xA0; e->raw[0x09]=0x80;
            gaw_ram_write16le(RAM_PLAYER_SPRITE_PTR,0xA241);
            W8(RAM_PLAYER_SPRITE_BANK,4);
            break;
        case 8:
            gaw_platform_audio_command(0x9A);
            memset(gaw_ram_ptr(0xC330),0,0x180); /* $2D7C: slots 1..8 */
            gaw_entity_set16(e,ENT_DELTA0,0); gaw_entity_set16(e,ENT_DELTA1,0);
            e->raw[ENT_MOTION_PHASE]=0x5A; e->raw[ENT_STATE]++;
            /* fall through */
        case 9: {
            e->raw[ENT_HIT_FLASH_TIMER]=0; e->raw[ENT_PENDING_DAMAGE]=0; e->raw[ENT_ANIM_FRAME]=0;
            e->raw[ENT_FLAGS]=(uint8_t)((e->raw[ENT_FLAGS]&~0x02u)|0x01u);
            unsigned idx=(R8(RAM_FRAME_COUNTER)&2u)?1u:0u;
            gaw_ram_write16le(RAM_PLAYER_SPRITE_PTR,player_sprite_death[idx]);
            W8(RAM_PLAYER_SPRITE_BANK,5); e->raw[0x08]=0xA0; e->raw[0x09]=0x80;
            if (e->raw[ENT_MOTION_PHASE]==0) { e->raw[ENT_FLAGS]&=(uint8_t)~1u; W8(RAM_MAIN_STATE,0x14); }
            break;
        }
        case 10:
            gaw_ram_write16le(0xC308,0x83E3); e->raw[ENT_ANIM_TICK]=0xFF; e->raw[ENT_ANIM_FRAME]=0; e->raw[ENT_STATE]++;
            /* fall through */
        case 11: {
            uint8_t t=(uint8_t)(e->raw[ENT_ANIM_TICK]+1u); e->raw[ENT_ANIM_TICK]=t;
            if (t==3) e->raw[ENT_STATE]=0;
            unsigned idx=(unsigned)(e->raw[ENT_DIRECTION]&3u)*2u + (R8(RAM_PLAYER_ENV_MODE)==2?1u:0u);
            gaw_ram_write16le(RAM_PLAYER_SPRITE_PTR,player_sprite_state11[idx]);
            W8(RAM_PLAYER_SPRITE_BANK,(uint8_t)(4u+(R8(RAM_PLAYER_ENV_MODE)==2)));
            break;
        }
        case 12:
            e->raw[ENT_ANIM_FRAME]=0; e->raw[ENT_FLAGS]|=1u; gaw_player_update_sprite_meta(e); break;
        default:
            break; /* states 0..12 are exhaustive in the original table */
    }
}


static GawEntity *player_entity_from_sms_pointer(uint16_t addr) {
    if (addr<RAM_ENTITIES || addr>=RAM_ENTITIES+GAW_ENTITY_COUNT*GAW_ENTITY_SIZE) return NULL;
    return (GawEntity *)(void *)gaw_ram_ptr(addr);
}

/* $37DA: snap Arthur back to the 8-pixel grid and push him away from the
   related entity unless the corresponding cached terrain byte blocks it. */
static void player_contact_realign(GawEntity *e, GawEntity *other) {
    uint8_t blocker;
    uint16_t pos_addr;
    int8_t push;
    if ((other->raw[ENT_DIRECTION]&0xFFu)<2u) {
        pos_addr=0xC311;
        if (e->raw[0x11] < other->raw[0x11]) {
            blocker=(uint8_t)(R8(0xC04D)|R8(0xC04B));
            if (e->raw[0x11]<0x11u) return;
            push=-8;
        } else {
            blocker=(uint8_t)(R8(0xC05D)|R8(0xC05B));
            if (e->raw[0x11]>=0xA0u) return;
            push=8;
        }
    } else {
        pos_addr=0xC313;
        if (e->raw[0x13] < other->raw[0x13]) {
            blocker=(uint8_t)(R8(0xC051)); /* B from LE word $C050 */
            if (e->raw[0x13]<0x11u) return;
            push=-8;
        } else {
            blocker=(uint8_t)(R8(0xC057)); /* B from LE word $C056 */
            if (e->raw[0x13]>=0xF0u) return;
            push=8;
        }
    }

    e->raw[0x13]=(uint8_t)((e->raw[0x13]+4u)&0xF8u);
    e->raw[0x11]=(uint8_t)((e->raw[0x11]+4u)&0xF8u);
    e->raw[ENT_ANIM_FRAME]=0;
    e->raw[ENT_MOTION_PHASE]=0;
    e->raw[ENT_STATE]=0;
    gaw_entity_set16(e,ENT_DELTA1,0);
    gaw_entity_set16(e,ENT_DELTA0,0);
    e->raw[ENT_ACCUM1]=0;
    e->raw[ENT_ACCUM0]=0;
    if ((blocker&0x80u)==0) W8(pos_addr,(uint8_t)(R8(pos_addr)+(uint8_t)push));
}

static int16_t entity_signed16(const GawEntity *e, unsigned off) {
    return (int16_t)gaw_entity_get16(e,off);
}

/* $2DF7-$2EDA: Arthur-specific collision consequence / knockback. */
static void player_contact_update(GawEntity *e) {
    if (e->raw[ENT_STATE]==9) return;
    if (e->raw[ENT_HP]==0) { e->raw[ENT_STATE]=8; return; }

    if (e->raw[ENT_PENDING_DAMAGE]!=0) {
        GawEntity *other=player_entity_from_sms_pointer(gaw_entity_get16(e,ENT_RELATED_PTR));
        if (other) {
            int handled_without_player_hit=0;
            if (other->raw[ENT_FLAGS]&0x10u) {
                uint8_t idx=R8(0xC0F2);
                uint8_t threshold=idx<sizeof player_contact_thresholds?player_contact_thresholds[idx]:0;
                if (threshold>=other->raw[ENT_ATTACK] && e->raw[ENT_STATE]==1 && R8(RAM_PLAYER_ENV_MODE)!=3) {
                    uint8_t dir=e->raw[ENT_DIRECTION]&3u;
                    unsigned off=(dir<2u)?ENT_DELTA0:ENT_DELTA1;
                    int16_t v=entity_signed16(other,off);
                    int sign_ok=(dir==0u || dir==2u)?(v>=0):(v<0);
                    if (v!=0 && sign_ok) {
                        gaw_entity_set16(other,off,(uint16_t)(-(int32_t)v));
                        other->raw[ENT_MOTION_PHASE]=0x0A;
                        other->raw[ENT_FLAGS]&=(uint8_t)~0x02u;
                        e->raw[ENT_PENDING_DAMAGE]=0;
                        W8(0xDE06,0x98);
                        handled_without_player_hit=1;
                    }
                }
                if (!handled_without_player_hit) {
                    player_contact_realign(e,other);
                    gaw_entity_clear(other);
                }
            } else {
                player_contact_realign(e,other);
            }
        }
    }

    if (R8(RAM_PLAYER_ENV_MODE)==4 && e->raw[ENT_HIT_FLASH_TIMER]==0)
        e->raw[ENT_PENDING_DAMAGE]=(uint8_t)(e->raw[ENT_PENDING_DAMAGE]+4u);
    if (e->raw[ENT_PENDING_DAMAGE]!=0) {
        e->raw[ENT_HIT_FLASH_TIMER]=0x30;
        W8(0xDE06,0x91);
    }
}

static int player_spend_resource(void) {
    static const uint8_t cost[4]={8,8,32,24};
    uint8_t v=R8(0xC0DB), c=cost[R8(0xC0DF)&3u];
    if (v<c) return 0;
    W8(0xC0DB,(uint8_t)(v-c)); return 1;
}


/* $3042/$308B: environment-mode-3 action clones Arthur into slot 1 and
   converts that copy to entity type 5. */
static int player_clone_to_slot1(GawEntity *e, uint8_t type) {
    GawEntity *slot1=gaw_entity(1);
    if (!slot1 || slot1->raw[ENT_TYPE]!=0) return 0;
    memcpy(slot1->raw,e->raw,GAW_ENTITY_SIZE);
    slot1->raw[ENT_TYPE]=type;
    slot1->raw[ENT_STATE]=0;
    slot1->raw[ENT_DELTA1]=0;
    slot1->raw[ENT_DELTA0]=0;
    slot1->raw[ENT_ANIM_FRAME]=0;
    return 1;
}

static void player_mode3_action(GawEntity *e) {
    if (!player_clone_to_slot1(e,5)) return;
    W8(0xDE06,0xAA);
}


static void player_inventory_refresh(void) {
    /* $7226 begins by selecting item 0; the rest is HUD/VRAM work. */
    W8(0xC0DF,0);
    gaw_platform_inventory_refresh();
}

static void player_action3_special(void) {
    if (R8(0xC072)==0 || R8(0xC0AD)!=0) return;
    W8(0xC0AD,1); W8(0xDE08,0xA9);
    gaw_platform_player_special_effect(3);
    player_inventory_refresh();
}

static void player_action_full_heal(GawEntity *e) {
    uint8_t cap=R8(0xC0DA);
    if (e->raw[ENT_HP]==cap) return;
    e->raw[ENT_HP]=cap; W8(0xC0E8,0);
    gaw_platform_player_special_effect(8);
    player_inventory_refresh();
}

static void player_action_transform_world(void) {
    if (R8(0xC040)!=0) return;
    W8(0xDE06,0xA4);
    unsigned changed=0;
    for (unsigned i=0;i<160;++i) if (R8((uint16_t)(0xDC00u+i))==0x3Fu) { W8((uint16_t)(0xDC00u+i),0x3A); ++changed; }
    if (changed) {
        gaw_platform_player_special_effect(10);
        for (unsigned i=16;i<32;++i) {
            GawEntity *x=gaw_entity(i); if (!x || x->raw[ENT_TYPE]==0) continue;
            if ((x->raw[ENT_FLAGS]&1u)==0) gaw_entity_clear(x);
            else {
                x->raw[ENT_SAVED_TYPE]=x->raw[ENT_TYPE]; x->raw[ENT_TYPE]=1;
                x->raw[ENT_COOLDOWN]=0; x->raw[ENT_STATE]=0;
                gaw_entity_set16(x,ENT_DELTA1,0); gaw_entity_set16(x,ENT_DELTA0,0);
                W8(0xDE08,0xA0);
            }
        }
    }
    if (R8(0xC0AC)==0) {
        W8(0xC0AC,1);
        memcpy(gaw_ram_ptr(0xCAC0),gaw_ram_ptr(0xC080),8);
        memcpy(gaw_ram_ptr(0xCAF0),gaw_ram_ptr(0xC088),8);
        uint8_t cell=(uint8_t)gaw_ram_read16le(RAM_WORLD_CELL_ID);
        if (cell==0x96u || cell==0xAAu || cell==0xCBu) {
            (void)gaw_world_progress_test_and_set();
            gaw_world_progress_restore_for_current_cell();
        }
    }
    gaw_world_expand_metatiles(); gaw_platform_world_rebuilt();
}

static void player_use_action(GawEntity *e) {
    uint8_t item=R8(0xC0DF);
    if (item>=12) return;
    switch (item) {
        case 0: e->raw[ENT_STATE]=2; gaw_platform_audio_command(0x90); break;
        case 1: e->raw[ENT_STATE]=4; gaw_platform_audio_command(0x99); break;
        case 2:
            if (R8(0xC0BF)) { W8(0xC0BF,0); W8(0xC0E2,0); W8(0xDE06,0x97); player_inventory_refresh(); }
            break;
        case 3:
            player_action3_special();
            break;
        case 4:
            if (gaw_entity(1)->raw[ENT_TYPE]!=0) break;
            if (R8(0xC0C6)==0 && !player_spend_resource()) { player_inventory_refresh(); break; }
            W8(0xC0C6,(uint8_t)((R8(0xC0C6)+1u)&3u));
            e->raw[ENT_STATE]=10; W8(0xDE06,0x92); (void)player_clone_to_slot1(e,3);
            break;
        case 5:
            if (gaw_entity(1)->raw[ENT_TYPE]!=0 || !player_spend_resource()) break;
            e->raw[ENT_STATE]=10; W8(0xDE06,0x93); (void)player_clone_to_slot1(e,4);
            break;
        case 6:
            if (!player_spend_resource()) break;
            W8(0xC090,R8(0xC0E6)); e->raw[ENT_STATE]=6; W8(0xDE06,0x94);
            break;
        case 7:
            if (player_spend_resource()) {
                W8(0xDE06,0x97);
                unsigned heal=(R8(RAM_PLAYER_ENV_MODE)==2)?32u:16u;
                unsigned hp=e->raw[ENT_HP]+heal, cap=R8(0xC0DA);
                e->raw[ENT_HP]=(uint8_t)(hp<cap?hp:cap);
            }
            break;
        case 8:
            player_action_full_heal(e);
            break;
        case 9:
            if (R8(0xC040)==0) { gaw_platform_player_special_effect(9); gaw_world_teleport(gaw_ram_read16le(0xC0C2)); player_inventory_refresh(); }
            break;
        case 10:
            player_action_transform_world();
            break;
        case 11:
            if (R8(0xC040)==0) { gaw_platform_show_world_map(); player_inventory_refresh(); }
            break;
        default:
            break;
    }
}

int gaw_player_handler(GawEntity *e) {
    player_environment_preprocess(e);
    player_grid_transition(e);

    if ((R8(RAM_INPUT_PRESSED)&0x20u) && e->raw[ENT_STATE]==1 && e->raw[ENT_HP]!=0 && R8(RAM_PLAYER_ENV_MODE)!=5) {
        if (R8(RAM_PLAYER_ENV_MODE)==3) player_mode3_action(e);
        else player_use_action(e);
    }

    player_state_dispatch(e);

    player_contact_update(e);
    return 1;
}
